groups:
- name: marzban_alerts
  rules:
  - alert: MarzbanUserKitHighValue
    expr: |
      {__name__=~"marzban_user_.*", job="users"} > 52428800
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: "Высокое значение для пользователя {{ $labels.__name__ | reReplaceAll \"marzban_user_\" \"\" }}"
      description: |
        Пользователь: {{ $labels.__name__ | reReplaceAll "marzban_user_" "" }}
        Текущее значение: {{ $value | humanize }}
        Порог: 50 MB за 1 час
        Источник: {{ $labels.instance }}