groups:
  - name: user_traffic_alerts
    interval: 30s
    rules:
      - alert: UserTrafficExceeds1GB
        expr: |
          (
            {__name__=~"marzban_user_.*", job="users"}
            > 1073741824
          )
          and
          (
            changes({__name__=~"marzban_user_.*", job="users"}[24h]) > 0
            or
            time() - clamp_max(timestamp({__name__=~"marzban_user_.*", job="users"}), time()) < 60
          )
        for: 0s
        labels:
          severity: warning
        annotations:
          summary: "Пользователь {{ $labels.__name__ }} превысил 1 GB"
          description: "Трафик пользователя {{ $labels.__name__ | reReplaceAll \"marzban_user_\" \"\" }} составляет {{ $value | humanize }} байт"