name: Deploy with Docker Compose

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Stop and remove old containers
        working-directory: ./prometheus-alert
        run: docker-compose down || true

      - name: Build and deploy with Docker Compose
        working-directory: ./prometheus-alert
        run: docker-compose up -d --build
      
      - name: Install requirements
        run: python3 -m venv venv || source venv/bin/activate || pip install -r requirements

       
      # - name: Prune unused images
      #   run: docker image prune -f