name: Deploy Prometheus

on:
  push:
    branches: [ "main" ]
    paths:
      - 'prometheus/**'
      - '.github/workflows/prometheus-deploy.yml'
  workflow_dispatch:

jobs:
  deploy_prometheus:
    runs-on: self-hosted
    environment:
      name: Env 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Stop and remove old containers
        working-directory: ./prometheus
        run: 
          docker stop pushgateway1 pushgateway2 prometheus || true
          docker-compose down || true

      - name: Build and deploy with Docker Composes
        working-directory: ./prometheus
        run: docker-compose up -d --build
      
      - name: Create virtual environment
        run: |
          python -m venv venv
          echo "Virtual environment created"

      - name: Activate venv and install dependencies
        run: |
          source venv/bin/activate
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Make env file
        run: |
          cat > .env << EOF
          GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          MARZBAN_URL=${{ vars.MARZBAN_URL }}
          MARZBAN_USERNAME=${{ secrets.MARZBAN_USERNAME }}
          MARZBAN_PASSWORD=${{ secrets.MARZBAN_PASSWORD }}
          PUSHGATEWAY_URL1=${{ vars.PUSHGATEWAY_URL1 }}
          PUSHGATEWAY_URL2=${{ vars.PUSHGATEWAY_URL2 }}
          CLIENT_CERT_PATH=${{ vars.CLIENT_CERT_PATH }}
          CLIENT_KEY_PATH=${{ vars.CLIENT_KEY_PATH }}
          EOF
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARZBAN_URL: ${{ vars.MARZBAN_URL }}
          MARZBAN_USERNAME: ${{ secrets.MARZBAN_USERNAME }}
          MARZBAN_PASSWORD: ${{ secrets.MARZBAN_PASSWORD }}
          PUSHGATEWAY_URL1: ${{ vars.PUSHGATEWAY_URL1 }}
          PUSHGATEWAY_URL2: ${{ vars.PUSHGATEWAY_URL2 }}
          CLIENT_CERT_PATH: ${{ vars.CLIENT_CERT_PATH }}
          CLIENT_KEY_PATH: ${{ vars.CLIENT_KEY_PATH }}
      
      - name: Move metrics.service and metrics.timer
        run: | 
          sudo mv metrics.service /etc/systemd/system/ 
          sudo mv metrics.timer /etc/systemd/system/
          mv reset.sh /home/john

      - name: Reload systemd 
        run: |
          sudo systemctl daemon-reload
          sudo systemctl enable metrics.timer
          sudo systemctl start metrics.timer